version: "3.9"
services:

  frontend:
    # Собираем образ из /frontend/Dockerfile
    build:
      context: ./frontend
    # Сохраняем образ с тегом latest
    image: app-frontend:latest
    # Открываем порт на localhost согласно переменной из .env файла
    ports:
      - "${FRONTEND_PORT}:80"
    # Передаем переменные окружения из .env файла
    environment:
      - NODE_ENV=${NODE_ENV}
    # монтируем nginx.conf из локальной папки
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend_network
    # рестарт сервиса  при ошибке
    restart: on-failure
    # Ожидание загрузки базы и бэкенда
    depends_on:
      - database
      - backend

  backend:
    # Собираем образ из /backend/Dockerfile 
    build:
      context: ./backend
    # Сохраняем образ с тегом latest
    image: app-backend:latest
    # Открываем порт на localhost согласно переменной из .env файла
    ports:
      - "${BACKEND_PORT}:3001"
    # Передаем переменные окружения из .env файла
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
    networks:
      - frontend_network
      - backend_network
    # рестарт сервиса  при ошибке
    restart: on-failure
    # Ожидание загрузки базы данных с хелсчекоком
    depends_on:
      database:
        condition: service_healthy

  database:
    # Собираем образ из /backend/Dockerfile
    build:
      context: ./database
    # Сохраняем образ с тегом latest
    image: app-database:latest
    # Передаем переменные окружения из .env файла
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # Монтируем volume и передаем данные БД
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      # Проверяем готовность базы командой pg_isready
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s     # Как часто проверять
      timeout: 5s      # Сколько ждать ответа
      retries: 5       # Сколько попыток до статуса "unhealthy"
      start_period: 10s # Время на начальную загрузку (init.sql)
    # рестарт сервиса  при ошибке
    restart: on-failure

# Создаем volume для БД
volumes:
  postgres_data:

# Создаем бридж сети frontend и backend
networks:
  backend_network:
    driver: bridge

  frontend_network:
    driver: bridge
